const express = require('express');
const router = express.Router();
const mongoose = require('mongoose');
const Patient = require('../models/Patient');
const Doctor = require('../models/Doctor');
const Appointment = require('../models/Appointment');
const Invoice = require('../models/Invoice');
const { protect } = require('../middleware/auth');
const { cacheMiddleware } = require('../config/cache');

/**
 * Generate PDF HTML report
 * This generates styled HTML that can be rendered as PDF client-side using html2pdf
 * or printed via window.print()
 */

// Helper: Generate styled HTML for reports
const generateReportHTML = (title, subtitle, columns, rows, summary = {}) => {
  const today = new Date().toLocaleDateString('en-US', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric'
  });

  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title} - Subhan Care HMS</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      color: #1e293b;
      background: #fff;
      padding: 40px;
      font-size: 12px;
      line-height: 1.5;
    }

    .header {
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
      border-bottom: 3px solid #2563eb;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    .header-left h1 {
      font-size: 24px;
      font-weight: 800;
      color: #1e40af;
      letter-spacing: -0.5px;
    }
    .header-left p {
      font-size: 11px;
      color: #64748b;
      margin-top: 4px;
    }
    .header-right {
      text-align: right;
      font-size: 11px;
      color: #64748b;
    }
    .header-right .date {
      font-weight: 700;
      color: #334155;
      font-size: 12px;
    }

    .report-title {
      background: linear-gradient(135deg, #eff6ff, #dbeafe);
      border: 1px solid #bfdbfe;
      border-radius: 8px;
      padding: 16px 20px;
      margin-bottom: 24px;
    }
    .report-title h2 {
      font-size: 16px;
      font-weight: 700;
      color: #1e40af;
    }
    .report-title p {
      font-size: 11px;
      color: #3b82f6;
      margin-top: 2px;
    }

    .summary-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
      gap: 12px;
      margin-bottom: 24px;
    }
    .summary-card {
      background: #f8fafc;
      border: 1px solid #e2e8f0;
      border-radius: 8px;
      padding: 14px 16px;
    }
    .summary-card .label {
      font-size: 10px;
      font-weight: 700;
      color: #94a3b8;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }
    .summary-card .value {
      font-size: 20px;
      font-weight: 800;
      color: #1e293b;
      margin-top: 4px;
    }

    table {
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 24px;
    }
    thead tr {
      background: #1e40af;
      color: white;
    }
    th {
      padding: 10px 14px;
      font-size: 11px;
      font-weight: 700;
      text-align: left;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }
    td {
      padding: 10px 14px;
      font-size: 12px;
      border-bottom: 1px solid #e2e8f0;
    }
    tbody tr:nth-child(even) {
      background: #f8fafc;
    }
    tbody tr:hover {
      background: #eff6ff;
    }

    .status-badge {
      display: inline-block;
      padding: 2px 10px;
      border-radius: 12px;
      font-size: 11px;
      font-weight: 700;
    }
    .status-scheduled, .status-paid {
      background: #dcfce7;
      color: #166534;
    }
    .status-cancelled, .status-unpaid {
      background: #fef2f2;
      color: #991b1b;
    }
    .status-completed {
      background: #dbeafe;
      color: #1e40af;
    }

    .footer {
      margin-top: 40px;
      padding-top: 16px;
      border-top: 2px solid #e2e8f0;
      display: flex;
      justify-content: space-between;
      font-size: 10px;
      color: #94a3b8;
    }
    .footer .confidential {
      font-weight: 700;
      color: #ef4444;
    }

    .total-row td {
      font-weight: 800;
      border-top: 2px solid #1e40af;
      background: #eff6ff;
    }

    @media print {
      body { padding: 20px; }
      .no-print { display: none; }
    }
  </style>
</head>
<body>

  <!-- Header -->
  <div class="header">
    <div class="header-left">
      <h1>🏥 Subhan Care Hospitals Ltd.</h1>
      <p>Hospital Management System — Official Report</p>
    </div>
    <div class="header-right">
      <div class="date">${today}</div>
      <div>Generated by Subhan Care HMS</div>
      <div>Report ID: RPT-${Date.now().toString(36).toUpperCase()}</div>
    </div>
  </div>

  <!-- Report Title -->
  <div class="report-title">
    <h2>${title}</h2>
    <p>${subtitle}</p>
  </div>

  <!-- Summary Cards -->
  ${Object.keys(summary).length > 0 ? `
  <div class="summary-grid">
    ${Object.entries(summary).map(([label, value]) => `
      <div class="summary-card">
        <div class="label">${label}</div>
        <div class="value">${value}</div>
      </div>
    `).join('')}
  </div>
  ` : ''}

  <!-- Data Table -->
  <table>
    <thead>
      <tr>
        ${columns.map(col => `<th>${col}</th>`).join('')}
      </tr>
    </thead>
    <tbody>
      ${rows.map(row => `
        <tr>
          ${row.map(cell => `<td>${cell}</td>`).join('')}
        </tr>
      `).join('')}
    </tbody>
  </table>

  <!-- Footer -->
  <div class="footer">
    <span class="confidential">⚠️ CONFIDENTIAL — For authorized personnel only</span>
    <span>© ${new Date().getFullYear()} Subhan Care Hospitals Ltd. All rights reserved.</span>
  </div>

</body>
</html>`;
};

// Helper: Status badge HTML
const statusBadge = (status) => {
  const cls = status.toLowerCase().replace(/\s/g, '-');
  return `<span class="status-badge status-${cls}">${status}</span>`;
};

// @desc    Generate report data for PDF export
// @route   GET /api/reports/generate?type=patients|doctors|appointments|invoices|revenue
// @access  Private
router.get('/generate', protect, cacheMiddleware(300), async (req, res) => {
  try {
    const { type = 'patients', startDate, endDate, status: statusFilter } = req.query;

    let patients, doctors, appointments, invoices;

    if (mongoose.connection.readyState === 1) {
      patients = await Patient.find({}).sort({ registeredDate: -1 });
      doctors = await Doctor.find({}).sort({ name: 1 });
      appointments = await Appointment.find({}).sort({ date: -1 });
      invoices = await Invoice.find({}).sort({ date: -1 });
    } else {
      const store = global.memoryStore;
      patients = store.patients || [];
      doctors = store.doctors || [];
      appointments = store.appointments || [];
      invoices = store.invoices || [];
    }

    let title, subtitle, columns, rows, summary;

    switch (type.toLowerCase()) {
      case 'patients': {
        let filtered = patients;
        if (startDate && endDate) {
          filtered = filtered.filter(p => p.registeredDate >= startDate && p.registeredDate <= endDate);
        }

        title = 'Patient Registry Report';
        subtitle = `Complete patient listing — ${filtered.length} records${startDate ? ` (${startDate} to ${endDate})` : ''}`;
        columns = ['#', 'Patient ID', 'Full Name', 'Gender', 'CNIC', 'Phone', 'Email', 'Blood Group', 'Registered'];
        rows = filtered.map((p, i) => [
          i + 1,
          p.id,
          p.name,
          p.gender,
          p.cnic || 'N/A',
          p.phone,
          p.email,
          p.bloodGroup,
          p.registeredDate || 'N/A'
        ]);
        summary = {
          'Total Patients': filtered.length,
          'Male': filtered.filter(p => p.gender === 'Male').length,
          'Female': filtered.filter(p => p.gender === 'Female').length,
          'Blood Groups': [...new Set(filtered.map(p => p.bloodGroup))].length + ' types'
        };
        break;
      }

      case 'doctors': {
        title = 'Medical Staff Directory';
        subtitle = `Physician roster — ${doctors.length} active doctors`;
        columns = ['#', 'Doctor ID', 'Name', 'Specialty', 'Phone', 'Email', 'Fee ($)', 'Rating', 'Consults'];
        rows = doctors.map((d, i) => [
          i + 1,
          d.id,
          d.name,
          d.specialty,
          d.phone,
          d.email,
          `$${d.fee}`,
          `⭐ ${(d.rating || 5).toFixed(1)}`,
          d.consultsCount || 0
        ]);
        const avgFee = doctors.length ? Math.round(doctors.reduce((s, d) => s + d.fee, 0) / doctors.length) : 0;
        summary = {
          'Total Doctors': doctors.length,
          'Average Fee': `$${avgFee}`,
          'Specialties': [...new Set(doctors.map(d => d.specialty))].length,
          'Total Consults': doctors.reduce((s, d) => s + (d.consultsCount || 0), 0)
        };
        break;
      }

      case 'appointments': {
        let filtered = appointments;
        if (startDate && endDate) {
          filtered = filtered.filter(a => a.date >= startDate && a.date <= endDate);
        }
        if (statusFilter && statusFilter !== 'All') {
          filtered = filtered.filter(a => a.status === statusFilter);
        }

        title = 'Appointments Schedule Report';
        subtitle = `Appointment records — ${filtered.length} entries${startDate ? ` (${startDate} to ${endDate})` : ''}`;
        columns = ['#', 'Appt ID', 'Patient', 'Doctor', 'Date', 'Time', 'Fee ($)', 'Status'];
        rows = filtered.map((a, i) => [
          i + 1,
          a.id,
          a.patientName,
          a.doctorName,
          a.date,
          a.time,
          `$${a.fee}`,
          statusBadge(a.status)
        ]);
        const totalFees = filtered.reduce((s, a) => s + a.fee, 0);
        summary = {
          'Total Appointments': filtered.length,
          'Scheduled': filtered.filter(a => a.status === 'Scheduled').length,
          'Cancelled': filtered.filter(a => a.status === 'Cancelled').length,
          'Total Fees': `$${totalFees.toLocaleString()}`
        };
        break;
      }

      case 'invoices': {
        let filtered = invoices;
        if (startDate && endDate) {
          filtered = filtered.filter(i => i.date >= startDate && i.date <= endDate);
        }
        if (statusFilter && statusFilter !== 'All') {
          filtered = filtered.filter(i => i.status === statusFilter);
        }

        title = 'Billing & Invoice Report';
        subtitle = `Invoice records — ${filtered.length} entries${startDate ? ` (${startDate} to ${endDate})` : ''}`;
        columns = ['#', 'Invoice ID', 'Patient', 'Issue Date', 'Due Date', 'Subtotal', 'Tax', 'Total ($)', 'Status'];
        rows = filtered.map((inv, i) => [
          i + 1,
          inv.id,
          inv.patientName,
          inv.date,
          inv.dueDate,
          `$${inv.subtotal}`,
          `${inv.taxRate}%`,
          `$${inv.totalAmount.toFixed(2)}`,
          statusBadge(inv.status)
        ]);
        const paidTotal = filtered.filter(i => i.status === 'Paid').reduce((s, i) => s + i.totalAmount, 0);
        const unpaidTotal = filtered.filter(i => i.status === 'Unpaid').reduce((s, i) => s + i.totalAmount, 0);
        summary = {
          'Total Invoices': filtered.length,
          'Paid': filtered.filter(i => i.status === 'Paid').length,
          'Unpaid': filtered.filter(i => i.status === 'Unpaid').length,
          'Revenue Collected': `$${paidTotal.toLocaleString()}`,
          'Outstanding': `$${unpaidTotal.toLocaleString()}`
        };
        break;
      }

      case 'revenue': {
        // Revenue summary report
        const paidInvoices = invoices.filter(i => i.status === 'Paid');
        const scheduledAppts = appointments.filter(a => a.status === 'Scheduled');
        const invoiceRevenue = paidInvoices.reduce((s, i) => s + i.totalAmount, 0);
        const apptRevenue = scheduledAppts.reduce((s, a) => s + a.fee, 0);

        title = 'Revenue Analytics Report';
        subtitle = `Financial overview — Generated ${new Date().toLocaleDateString()}`;
        columns = ['Category', 'Count', 'Revenue ($)'];
        rows = [
          ['Paid Invoices', paidInvoices.length, `$${invoiceRevenue.toLocaleString()}`],
          ['Scheduled Appointments', scheduledAppts.length, `$${apptRevenue.toLocaleString()}`],
          ['<strong>Grand Total</strong>', paidInvoices.length + scheduledAppts.length, `<strong>$${(invoiceRevenue + apptRevenue).toLocaleString()}</strong>`]
        ];
        summary = {
          'Total Revenue': `$${(invoiceRevenue + apptRevenue).toLocaleString()}`,
          'Invoice Revenue': `$${invoiceRevenue.toLocaleString()}`,
          'Appointment Revenue': `$${apptRevenue.toLocaleString()}`,
          'Active Patients': patients.length,
          'Active Doctors': doctors.length
        };
        break;
      }

      default:
        return res.status(400).json({ success: false, error: 'Invalid report type' });
    }

    const html = generateReportHTML(title, subtitle, columns, rows, summary);

    res.json({
      success: true,
      html,
      meta: { title, recordCount: rows.length, generatedAt: new Date().toISOString() }
    });

  } catch (error) {
    console.error('Report generation error:', error);
    res.status(500).json({ success: false, error: error.message });
  }
});

module.exports = router;
